import { writeFileSync } from 'fs';

const db = [
  { id:1, q:"What is an election?", k:["what is election","election mean","define election"], s:"An election is a formal process where people vote to choose their leaders.", d:"An election is a democratic process through which citizens choose representatives to govern them. In India, elections are conducted by the Election Commission of India (ECI) at various levels — national (Lok Sabha), state (Vidhan Sabha), and local (Panchayat/Municipal).", e:"Imagine your class needs a monitor. Everyone raises hands or votes — that's an election! Adults do the same to pick their leaders." },
  { id:2, q:"Why are elections important?", k:["why elections","importance of election","election matter"], s:"Elections give citizens the power to choose and change their government peacefully.", d:"Elections are the foundation of democracy. They ensure accountability of leaders, peaceful transfer of power, representation of all sections of society, and the ability of citizens to remove ineffective governments without violence.", e:"If your class monitor was being unfair, elections let you vote for someone better next time. That's the whole point!" },
  { id:3, q:"What is democracy?", k:["democracy","democratic","what is democracy"], s:"Democracy is a system where the government is chosen by the people through free and fair elections.", d:"Democracy (from Greek: demos = people, kratos = rule) is a system of government where citizens exercise power by voting. India is the world's largest democracy. Key features: free elections, fundamental rights, rule of law, independent judiciary, and freedom of press.", e:"Democracy means the people are the boss. The government works for you, not the other way around!" },
  { id:4, q:"What is voting?", k:["what is voting","voting mean","define voting"], s:"Voting is the act of expressing your choice in an election by marking a ballot or pressing an EVM button.", d:"Voting is the fundamental act of democratic participation. In India, eligible citizens cast their vote at a designated polling booth by pressing a button on the EVM next to their chosen candidate's name/symbol. Each vote carries equal weight regardless of caste, class, or gender.", e:"Voting is like picking your favorite option in a poll, but it actually decides who runs your city, state, or country!" },
  { id:5, q:"What is universal adult franchise?", k:["universal adult franchise","adult franchise","franchise"], s:"Universal adult franchise means every adult citizen has the right to vote, regardless of gender, caste, religion, or wealth.", d:"Universal Adult Franchise means the right to vote is given to all adult citizens without any discrimination. India adopted this from independence in 1950. The minimum voting age was reduced from 21 to 18 in 1989 via the 61st Constitutional Amendment.", e:"It means EVERYONE who is 18+ gets a vote. Rich or poor, man or woman — one person, one vote. Always equal." },
  { id:6, q:"Who can vote in India?", k:["who can vote","eligible to vote","voting eligibility"], s:"Any Indian citizen aged 18+ who is registered as a voter in the electoral roll.", d:"To vote in India you must: (1) be an Indian citizen, (2) be at least 18 years old as of January 1 of the election year, (3) be of sound mind, (4) be registered in the electoral roll of a constituency. Note: persons under preventive detention or serving criminal sentences may be restricted.", e:"If you're 18 or older, you're an Indian citizen, and your name is on the voter list — you can vote!" },
  { id:7, q:"What is the legal voting age in India?", k:["voting age","age to vote","minimum age vote"], s:"18 years.", d:"The minimum voting age in India is 18 years. This was established by the 61st Constitutional Amendment Act of 1988, which came into effect in 1989. Previously it was 21 years. The qualifying date is January 1 of the year the electoral roll is updated.", e:"You need to be at least 18 years old. The day you turn 18, you earn the right to vote!" },
  { id:8, q:"What is the Election Commission of India?", k:["eci","election commission","what is eci"], s:"An independent constitutional body that oversees all elections in India.", d:"The Election Commission of India (ECI) was established on January 25, 1950 under Article 324 of the Constitution. It is a permanent, independent body that conducts Lok Sabha, Rajya Sabha, State Legislative Assembly, and Presidential & Vice-Presidential elections. It has full authority over the electoral process.", e:"Think of ECI as the 'referee' of elections — it makes sure the game (election) is played fairly by everyone." },
  { id:9, q:"What does ECI do?", k:["what does eci do","role of eci","election commission role"], s:"ECI announces election dates, enforces the Model Code of Conduct, manages EVMs, and ensures free & fair elections.", d:"ECI's key functions: (1) Prepares and updates electoral rolls, (2) Announces election schedules, (3) Enforces Model Code of Conduct, (4) Registers political parties and assigns symbols, (5) Monitors election expenditure, (6) Deploys EVMs and VVPAT machines, (7) Adjudicates disputes during elections.", e:"ECI makes the rules, watches the game, and gives red cards to anyone who cheats in elections!" },
  { id:10, q:"What are free and fair elections?", k:["free fair election","free election","fair election"], s:"Elections where all eligible citizens can vote freely without fear, coercion, or manipulation.", d:"Free and fair elections require: (1) Universal suffrage, (2) Secret ballot, (3) Independent election management, (4) Transparent counting, (5) Equal access to media, (6) Prevention of voter intimidation, (7) Independent judiciary to resolve disputes. India's ECI works to ensure all these conditions.", e:"Imagine a school vote where no one forces you, no one peeks at your choice, and every vote is counted honestly. That's free and fair!" },
  { id:11, q:"What is Lok Sabha?", k:["lok sabha","lower house","house of the people"], s:"The lower house of India's Parliament, directly elected by citizens.", d:"Lok Sabha (House of the People) is the lower house of India's bicameral Parliament. Key facts: 543 elected seats + 2 nominated (Anglo-Indian, now discontinued); Members are directly elected by voters in constituencies; Maximum term is 5 years; Can be dissolved earlier by the President on advice of PM; Controls the budget and is more powerful than Rajya Sabha on money bills.", e:"Lok Sabha is like the main team in Parliament. The people you directly vote for go there. 543 seats, 5-year terms." },
  { id:12, q:"What is Rajya Sabha?", k:["rajya sabha","upper house","council of states"], s:"The upper house of India's Parliament, indirectly elected by state legislatures.", d:"Rajya Sabha (Council of States) is the upper house of India's Parliament. Key facts: 245 seats (233 elected + 12 nominated by President); Members are elected by elected MLAs of state legislative assemblies; Rajya Sabha is permanent — it cannot be dissolved; Members serve 6-year terms, with 1/3rd retiring every 2 years.", e:"Rajya Sabha is like a review board for laws. State governments send people there (not direct public vote). It never fully shuts down." },
  { id:13, q:"Difference between Lok Sabha and Rajya Sabha?", k:["difference lok sabha rajya sabha","lok vs rajya","compare lok rajya"], s:"Lok Sabha is directly elected, more powerful, can be dissolved. Rajya Sabha is indirectly elected, permanent, reviews laws.", d:"Key differences: (1) Election: Lok Sabha by public directly; Rajya Sabha by MLAs. (2) Term: Lok Sabha 5 years; Rajya Sabha 6 years (staggered). (3) Dissolution: Lok Sabha can be dissolved; Rajya Sabha cannot. (4) Power: Lok Sabha is supreme on money bills; Rajya Sabha can delay but not block. (5) Size: Lok Sabha 543 seats; Rajya Sabha 245 seats.", e:"Lok Sabha = directly voted by you, more powerful. Rajya Sabha = chosen by state representatives, reviews and suggests changes to laws." },
  { id:14, q:"What is Vidhan Sabha?", k:["vidhan sabha","state assembly","state legislature","legislative assembly"], s:"The state-level equivalent of Lok Sabha — the lower house of a state legislature, directly elected by voters.", d:"Vidhan Sabha (State Legislative Assembly) is the lower house of state legislatures in India. Members are directly elected by voters in state constituencies. The number of seats varies by state (e.g., UP has 403, Goa has 40). MLAs are elected for 5-year terms. Most state governments are formed by the party with majority in Vidhan Sabha.", e:"Just like you vote for MPs for Parliament, you vote for MLAs for the Vidhan Sabha — but it only runs your state, not the whole country." },
  { id:15, q:"Who is an MP?", k:["who is mp","member of parliament","what is mp"], s:"A Member of Parliament (MP) is an elected representative in Lok Sabha or Rajya Sabha.", d:"An MP (Member of Parliament) represents a constituency at the national level. Lok Sabha MPs are directly elected by citizens of a constituency every 5 years. Rajya Sabha MPs are elected by MLAs every 6 years. MPs participate in law-making, budget debates, and question the government in Parliament.", e:"An MP is your voice in the country's main decision-making room. You vote them in to speak for your area in Parliament." },
  { id:16, q:"Who is an MLA?", k:["who is mla","member legislative assembly","what is mla"], s:"A Member of the Legislative Assembly (MLA) is an elected representative in a state's Vidhan Sabha.", d:"An MLA (Member of Legislative Assembly) represents a constituency at the state level. They are directly elected by voters every 5 years. MLAs make state laws, debate the state budget, elect members to Rajya Sabha, and the majority party's MLAs elect the Chief Minister.", e:"An MLA is your voice in your state government. They handle state issues like roads, schools, and hospitals in your area." },
  { id:17, q:"Difference between MP and MLA?", k:["mp vs mla","difference mp mla","mp and mla"], s:"MPs work at the national level in Parliament; MLAs work at the state level in Vidhan Sabha.", d:"Key differences: (1) Level: MP = national; MLA = state. (2) House: MP sits in Lok/Rajya Sabha; MLA sits in Vidhan Sabha. (3) Salary: MPs earn more (₹1 lakh/month + allowances) vs MLAs (varies by state). (4) Issues: MPs deal with national policies; MLAs handle state matters like local infrastructure, education, health. (5) Election: Both directly elected (except Rajya Sabha MPs).", e:"MP = works for the whole country. MLA = works for your state. Both are elected by you (voters)!" },
  { id:18, q:"What is a constituency?", k:["constituency","what is constituency","define constituency"], s:"A constituency is a defined geographic area whose residents elect one representative to a legislature.", d:"India is divided into constituencies for elections. For Lok Sabha: 543 constituencies across India, each electing 1 MP. For state elections: each state is divided into assembly constituencies electing MLAs. Delimitation Commission periodically redraws constituency boundaries based on population.", e:"Think of India cut into 543 puzzle pieces. Each piece is a constituency, and the people in each piece vote for their own MP." },
  { id:19, q:"How do I vote?", k:["how to vote","voting steps","how vote works","cast vote","voting process"], s:"Go to your assigned polling booth, show ID, get ink on your finger, press the EVM button next to your chosen candidate.", d:"Step-by-step: (1) Find your polling booth (check voter ID or voters.eci.gov.in). (2) Carry a valid photo ID. (3) Join the queue. (4) The officer verifies your name in the electoral roll. (5) Indelible ink is applied to your left index finger. (6) You press the button on the EVM next to your candidate. (7) VVPAT shows a slip for 7 seconds to confirm. Done!", e:"Show up, show your ID, get your finger inked so you can't vote twice, then press your candidate's button on the machine. Simple!" },
  { id:20, q:"What documents are needed to vote?", k:["documents for voting","id for voting","what to carry voting"], s:"Your Voter ID (EPIC card) OR any of 12 alternative photo IDs like Aadhaar, Passport, or Driving License.", d:"Primary: Voter ID (EPIC card). Alternative IDs accepted: Aadhaar card, Passport, Driving License, PAN card, MNREGA job card, Bank/Post Office passbook with photo, Smart card (CGHS/ECHS), Pension documents with photo, NPR Smart card, Official identity card issued by Central/State Govt., Disability ID card. Your name must be in the electoral roll.", e:"Bring your Voter ID — or if you don't have it, Aadhaar or passport works too! Just make sure your name is on the voter list." },
  { id:21, q:"What is a voter ID card?", k:["voter id","voter card","epic card","voter id card"], s:"An official photo identity card (EPIC) issued by the Election Commission to registered voters.", d:"The Voter ID card, officially called EPIC (Elector's Photo Identity Card), is issued free of cost by the Election Commission of India to all registered voters. It contains your photo, name, father's/husband's name, date of birth, address, and unique voter ID number. It serves both as identity proof and facilitates voting.", e:"It's your official 'I am a voter' card from the government. It has your photo and helps you vote at your polling booth." },
  { id:22, q:"Can I vote without voter ID?", k:["vote without voter id","no voter id","lost voter id"], s:"Yes! 12 alternative photo ID documents are accepted at polling booths.", d:"You can vote without the Voter ID (EPIC) card as long as your name is in the electoral roll. Present any of these: Aadhaar card, Passport, Driving License, PAN card, MNREGA Job Card, Bank passbook with photo, Pension document with photo, Smart card (CGHS/ECHS), NPR smart card, government-issued photo ID, disability ID, or service photo ID.", e:"Lost your voter card? No worries! Show your Aadhaar or driving license — as long as your name is on the list, you can vote." },
  { id:23, q:"How do I register to vote?", k:["register voter","voter registration","how to register","sign up voter","form 6"], s:"Apply online at voters.eci.gov.in using Form 6, or submit at your local Electoral Registration Office.", d:"To register: (1) Visit voters.eci.gov.in or download the Voter Helpline App. (2) Click 'New Voter Registration' and fill Form 6. (3) Upload: Aadhaar/DOB proof, address proof, and passport photo. (4) Submit online or at your local ERO office. (5) Track your application with the Reference Number. (6) Receive your EPIC card within 30 days after verification.", e:"Go to the government voter website, fill a form, upload your ID, and wait for your voter card to arrive at home. That's it!" },
  { id:24, q:"What is Form 6?", k:["form 6","what is form 6","form six"], s:"Form 6 is the official application form for new voter registration in India.", d:"Form 6 is used by citizens applying to be included in the electoral roll for the first time. It must be submitted to the Electoral Registration Officer (ERO) of the constituency where you normally reside. You need: proof of age, proof of address, and a recent photograph. Available online at voters.eci.gov.in and at local ERO offices.", e:"Form 6 is just the application you fill out to get added to the voter list for the first time. Like a sign-up form for voting!" },
  { id:25, q:"What if my name is missing from the voter list?", k:["name missing voter list","not in voter list","name not found","missing from list"], s:"Request a Tender Vote (Provisional Ballot), contact the Presiding Officer, or file a complaint with the ERO.", d:"If your name is missing: (1) Stay calm and ask the Presiding Officer to check thoroughly. (2) If still not found, request a 'Tender Vote' — a provisional ballot you can cast, which is kept separate and counted only if it affects the result. (3) Contact your constituency's ERO to investigate. (4) For future elections, register online at voters.eci.gov.in using Form 6.", e:"Don't give up! Tell the officer at the booth. You can ask for a 'Tender Vote' even if your name is missing. And fix it for next time by re-registering." },
  { id:26, q:"What is an EVM?", k:["evm","electronic voting machine","voting machine","evm machine"], s:"An Electronic Voting Machine (EVM) is a tamper-proof device used to cast and count votes in Indian elections.", d:"An EVM consists of two units: (1) Control Unit — operated by the Presiding Officer to manage the voting process. (2) Ballot Unit — placed in the voting compartment where voters press the button. EVMs have no internet/Bluetooth connectivity, use one-time programmable chips, and can record up to 3,840 votes. They replaced paper ballots from 2001 onwards.", e:"EVM is like a super-secure voting calculator. You press a button for your candidate and it silently counts your vote. No paper, no mess!" },
  { id:27, q:"How does an EVM work?", k:["how evm works","evm working","evm mechanism"], s:"Voters press a button next to their candidate's name on the Ballot Unit, which records the vote in the Control Unit.", d:"EVM operation: (1) The Presiding Officer presses the 'Ballot' button on the Control Unit to enable voting. (2) The voter presses the candidate's button on the Ballot Unit. (3) A red light glows and a beep confirms the vote is recorded. (4) The machine is locked until the next voter is enabled. All votes are stored in encrypted memory and counted after election using the Control Unit.", e:"The officer unlocks the machine, you press your candidate's button, it beeps and locks — your vote is safely stored inside!" },
  { id:28, q:"What is VVPAT?", k:["vvpat","paper trail","voter verified","vvpat machine"], s:"Voter Verified Paper Audit Trail — a machine that prints and displays a slip showing who you voted for, for 7 seconds.", d:"VVPAT (Voter Verified Paper Audit Trail) is attached to every EVM. After pressing the EVM button, a paper slip is printed showing the candidate's name, serial number, and symbol. It's visible through a glass window for 7 seconds, then drops into a sealed compartment. Introduced in 2013, it provides an independent audit trail for election verification.", e:"After you vote, a small machine shows a paper slip for 7 seconds saying who you voted for. It's like a receipt — proof your vote was counted correctly!" },
  { id:29, q:"Can EVMs be hacked?", k:["evm hacked","hack evm","evm tampered","evm manipulation"], s:"No. EVMs have no wireless connectivity and use one-time programmable chips that cannot be altered after programming.", d:"EVMs cannot be remotely hacked because: (1) They have zero internet, Wi-Fi, or Bluetooth components. (2) They use one-time programmable (OTP) microcontrollers — the code cannot be rewritten. (3) They are stored in double-locked strong rooms with 24/7 CCTV. (4) All parties can appoint agents to observe storage and counting. (5) Mock polls are conducted before each election for verification.", e:"EVMs are like a sealed box with no door to the internet. There's nothing to hack into remotely — it's physically impossible!" },
  { id:30, q:"What is the Model Code of Conduct?", k:["mcc","model code of conduct","code of conduct election","election rules conduct"], s:"A set of guidelines issued by ECI that all political parties and candidates must follow from election announcement until results.", d:"The MCC covers: (1) General conduct — no personal attacks, religion-based appeals, or voter bribing. (2) Government: no new schemes or project inaugurations for political gain. (3) Polling day: no campaigning within 48 hours of voting (silent period). (4) Party in power: cannot use government machinery for campaigns. Violations can lead to FIRs, warnings, or disqualification.", e:"MCC is the election rulebook. Once election dates are announced, politicians must play fair — no freebies, no religious speeches, no misusing government resources." },
  { id:31, q:"What is NOTA?", k:["nota","none of the above","reject candidate"], s:"NOTA (None of the Above) allows voters to formally reject all candidates without abstaining.", d:"NOTA was introduced by the Supreme Court of India in 2013. It appears as the last option on EVMs. Important: NOTA has no legal effect — even if NOTA gets the most votes, the candidate with the highest vote count among contestants wins. In 2019 elections, over 65 lakh (1.06%) votes were cast for NOTA. It primarily sends a moral message to political parties.", e:"NOTA is the 'I don't like any of these people' option. You still vote (participate), but for nobody. It shows parties people aren't happy with their choices." },
  { id:32, q:"Who can contest elections?", k:["who can contest","election eligibility candidate","contest election","stand for election"], s:"Any Indian citizen who meets the age requirement, is a registered voter, and is not disqualified under law.", d:"To contest Lok Sabha: must be Indian citizen, at least 25 years old, a voter anywhere in India, and not hold a government office of profit. For Rajya Sabha: 30 years minimum. Disqualifications include: unsound mind (court-declared), undischarged insolvent, holding office of profit, foreign citizenship, or conviction with 2+ year sentence.", e:"If you're 25+, Indian, and not a government employee or convicted criminal, you can try to become an MP! It's open to all." },
  { id:33, q:"Why should first-time voters vote?", k:["first time voter","why vote","should i vote","importance of voting"], s:"Your vote directly shapes who governs your city, state, and country. First-time voters can tip election results.", d:"Every vote matters: (1) Many elections are won by small margins — your single vote can make a difference. (2) Young voters' priorities (jobs, education, climate) get ignored if they don't vote. (3) Voting is your constitutional right AND civic duty. (4) Low youth turnout means older demographics dominate policy decisions. (5) First-time voter campaigns are showing results — 2019 saw record turnout of 67.4%.", e:"Imagine your school canteen menu was decided by a vote but you didn't vote. Then you can't complain about the food! Same logic applies to the country." },
  { id:34, q:"Can NRIs vote?", k:["nri vote","overseas vote","indian abroad vote"], s:"Yes, NRIs can vote but must be physically present in India at their registered constituency on election day.", d:"NRIs (Non-Resident Indians) retain their voting rights. To vote: (1) Register using Form 6A at voters.eci.gov.in. (2) Their name is added to the electoral roll of their hometown constituency. (3) They must physically travel to India and their polling booth to vote. Currently, proxy voting (voting from abroad) is NOT allowed, though legislation has been proposed.", e:"NRIs CAN vote in India, but they have to physically come back to India and go to their home constituency to cast the vote. No remote voting yet!" },
  { id:35, q:"What is a coalition government?", k:["coalition","coalition government","coalition meaning","minority government"], s:"A coalition government is formed when no single party wins enough seats for majority, so multiple parties join together to govern.", d:"A coalition government forms when: No single party gets 272+ seats (simple majority) in Lok Sabha. Multiple parties form an alliance, negotiate a Common Minimum Programme, and jointly form the government. Examples: NDA (1999-2004), UPA (2004-2014), NDA (2024-present). The President invites the leader of the largest coalition to form government.", e:"Imagine no single team won the tournament, so 3 teams joined together and share the trophy. That's a coalition — parties teaming up to rule together." },
  { id:36, q:"What is a hung parliament?", k:["hung parliament","hung assembly","no majority"], s:"A situation where no party or coalition has enough seats to form a majority government.", d:"A hung parliament occurs when no single party or pre-election alliance wins 272+ seats in Lok Sabha. The President then invites the single largest party to form government and prove majority within a time limit. If no one can prove majority, fresh elections may be called. India experienced hung parliaments in 1989 (V.P. Singh govt), 1996, and 1998.", e:"It's like a class election where 3 candidates each got nearly equal votes and nobody has a clear winner. Everyone's stuck — hung parliament!" },
  { id:37, q:"What is fake news during elections?", k:["fake news election","misinformation election","false information voting"], s:"Fabricated or misleading information spread to influence voters or create confusion during election campaigns.", d:"Election fake news includes: (1) False claims about candidates (fake criminal records, morphed photos). (2) Incorrect voting dates/locations to confuse voters. (3) Fabricated ECI announcements. (4) Deepfake videos of politicians. To verify: check PIB Fact Check (pib.gov.in), use Fact Check India on social media, or verify with official ECI channels. Report fakes to the ECI's cVIGIL app.", e:"During elections, some people spread lies on WhatsApp/Instagram to trick voters. Always check if news is from official sources before sharing!" },
  { id:38, q:"What are exit polls?", k:["exit poll","exit polls","what is exit poll"], s:"Surveys conducted right after voters leave polling booths to predict election results before the official count.", d:"Exit polls are conducted by research agencies/media outlets by sampling voters as they exit polling booths. They ask who the voter chose. Results are published after voting ends (not during, as ECI prohibits it). They are predictions, not results — they can be wrong. The ECI prohibits publishing exit polls until voting ends in all phases of a multi-phase election.", e:"After you vote and leave the booth, a researcher might ask 'Who did you vote for?' Their answers are analyzed to guess who'll win. It's like a quick preview before the real result!" },
  { id:39, q:"How are election results declared?", k:["election results","how results declared","counting day","result declaration"], s:"Counting begins on Counting Day at Counting Centres, watched by agents of all candidates, and results are declared as constituencies finish counting.", d:"After voting ends: (1) EVMs are stored in strong rooms with security and candidate agents present. (2) On Counting Day, EVMs are brought to Counting Centres. (3) VVPAT slips of 5 random booths per constituency are manually verified. (4) Votes are counted in rounds on EVM. (5) When a candidate exceeds the 'winning margin', the Returning Officer declares them elected. (6) ECI announces final results.", e:"On counting day, all the sealed voting machines are opened and counted in a big hall. Everyone watches. The one with most votes wins and is announced officially!" },
  { id:40, q:"What happens if no party gets majority?", k:["no majority","president rule","no clear winner","hung parliament formation"], s:"The President invites the largest party/coalition to prove majority. If unsuccessful, President's Rule may be imposed.", d:"Process when no majority: (1) President invites the single largest party to form government. (2) That party must prove majority within 15 days via floor test in Lok Sabha. (3) If they fail, the second-largest coalition gets a chance. (4) If everyone fails, fresh elections are called (or President's Rule in states). This is governed by Article 75 (for Centre) and Article 164 (for states) of the Constitution.", e:"If nobody wins enough seats, it's like no team got more than half the points. The President picks the team closest to majority and says: 'Try to get others on your side in 15 days!'" }
];

const toTS = (db) => {
  const items = db.map(item => 
    `  { id:${item.id}, question:${JSON.stringify(item.q)}, short_answer:${JSON.stringify(item.s)}, detailed_answer:${JSON.stringify(item.d)}, eli18_answer:${JSON.stringify(item.e)}, category:"General", keywords:${JSON.stringify(item.k)} }`
  ).join(',\n');
  return `export interface QAPair {
  id: number;
  question: string;
  short_answer: string;
  detailed_answer: string;
  eli18_answer: string;
  category: string;
  keywords: string[];
}

export const ELECTION_QA_DB: QAPair[] = [
${items}
];

export const MASTER_SYSTEM_PROMPT = \`You are Election Copilot.\`;

export const FALLBACK_RESPONSE = "Great question! I can help you with voter registration, EVMs, voting process, election results, parliament, constituencies, and more. Try asking something specific like 'How do I register to vote?' or 'What is an EVM?'";
`;
};

writeFileSync('./src/lib/constants.ts', toTS(db));
console.log('✅ constants.ts generated with', db.length, 'Q&A entries');
